spring.application.name=logica-app

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/logica_app}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:logica_app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:logica_app}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
server.error.include-stacktrace=never
